tproject/tapp/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from . import views

app_name = 'tapp'

urlpatterns = [
    path("uid-<int:user_id>/", views.get_clients, name='get_clients'),
    path("uid-<int:user_id>/cid-<int:client_id>/", views.get_clients_info, name="get_clients_info"),
    path("uid-<int:user_id>/cid-<int:client_id>/delete", views.delete_client, name="delete_client"),
    path("uid-<int:user_id>/cid-<int:client_id>/yandex-direct/", views.about_yandex_direct, name="about_yandex_direct"),
    url(r"^yandex-direct/code/", views.yandex_code, name="yandex_code"),
    url(r"^yandex-direct/token/", views.yandex_token, name="yandex_token"),
    # url(r"^login/yandex/$", views.YandexDirectCode),
    # url(r"^login/yandex/user/", views.YandexDirectUser)
]

tproject/tproject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include

urlpatterns = [
    path('admin/', admin.site.urls),
    url('tapp/', include("tapp.urls")),
]

tproject/tapp/models.py
from django.db import models

# Create your models here.


class YandexDirect(models.Model):
    token = models.CharField(max_length=256)
    client_id = models.CharField(max_length=256)
    user_first_name = models.CharField(max_length=256)
    user_last_name = models.CharField(max_length=256)
    user_email = models.CharField(max_length=256)
    create = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    user_id = models.IntegerField()

    def __str__(self):
        return f"{self.user_first_name} {self.user_last_name}"


class User(models.Model):
    user_name = models.CharField(max_length=256)
    user_surname = models.CharField(max_length=256)
    user_create = models.DateTimeField(auto_now_add=True)
    user_update = models.DateTimeField(auto_now=True)
    user_id = models.IntegerField()

    def __str__(self):
        return f"{self.user_name} {self.user_surname}"


class Client(models.Model):
    client_name = models.CharField(max_length=256)
    client_id = models.IntegerField()
    user_id = models.IntegerField()

    def __str__(self):
        return self.client_name

tproject/tapp/forms.py
from django import forms
from . import models
import random


class AddClientForm(forms.Form):
    # all_clients = models.Client.objects.all()
    # all_client_id = [client.client_id for client in all_clients]
    client_name = forms.CharField(max_length=256)
    client_id = forms.IntegerField()
    user_id = forms.IntegerField()
    # client_id = random.choice(list(set(range(1000)) - set(all_client_id)))

tproject/tapp/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect
from . import models
import requests, json, os, random
from django.conf import settings
from yaml import load


with open(os.path.join(settings.BASE_DIR, 'tapp/config.yaml')) as f:
    config = load(f)

# Create your views here.

YANDEX_KEY_ID = config['yandex']['YANDEX_KEY_ID']
YANDEX_SECRET_KEY = config['yandex']['YANDEX_SECRET_KEY']


def get_clients(request, user_id):
    if request.method == "POST":
        client_name = request.POST['client_name']

        all_clients = models.Client.objects.all()
        all_client_id = [client.client_id for client in all_clients]
        client_id = random.choice(list(set(range(1000)) - set(all_client_id)))

        client = models.Client(client_name=client_name, client_id=client_id, user_id=user_id)
        client.save()
    all_clients = models.Client.objects.all()
    return render(request, 'tapp/clients.html', context={"all_clients": all_clients})


def delete_client(request, user_id, client_id):
    client = models.Client.objects.get(user_id=user_id)
    client.delete()
    return HttpResponseRedirect(reverse('tapp:get_clients', args=(user_id, )))


def get_clients_info(request, user_id, client_id):
    try:
        yandex_direct = models.YandexDirect.objects.all().filter(user_id=user_id)
        client = models.Client.objects.get(client_id=client_id)
        context = {"yandex_direct": yandex_direct, "client": client.client_name, "user_id": user_id,
                   "client_id": client_id}
    except (KeyError, models.YandexDirect.DoesNotExist):
        client = models.Client.objects.get(user_id=user_id)
        context = {"client": client.client_name, "user_id": user_id,
                   "client_id": client_id}
    return render(request, 'tapp/client_info.html', context=context)


def about_yandex_direct(request, user_id, client_id):
    yandex = models.YandexDirect.objects.all().filter(user_id=user_id)
    return render(request, 'tapp/about_yandex_direct.html', context={"yandex": yandex})


def yandex_code(request):
    url = f"https://oauth.yandex.ru/authorize/?response_type=code&client_id={YANDEX_KEY_ID}"
    return HttpResponseRedirect(url)


def yandex_token(request):
    code = request.GET['code']
    headers = {"grant_type": "authorization_code", "code": code, "client_id": YANDEX_KEY_ID,
              "client_secret": YANDEX_SECRET_KEY}
    response = requests.post("https://oauth.yandex.ru/token", headers).json()
    passport = requests.get('https://login.yandex.ru/info', params={"format": "json",
                                                                    "oauth_token": response['access_token']}).json()

    data = {"login": passport['login'], "last_name": passport['last_name'], "first_name": passport['first_name'],
             "token": response['access_token'], "user_id": passport['id'], 'email': passport['default_email']}

    user = models.User.objects.get(pk=1)

    try:
        person = models.YandexDirect.objects.get(user_email=data['email'])
        person.token = data['token']
        person.save()
    except (KeyError, models.YandexDirect.DoesNotExist):
        models.YandexDirect.objects.create(token=data['token'], user_first_name=data['first_name'],
                                            user_last_name=data['last_name'], user_email=data['email'],
                                            user_id=user.user_id)

    return HttpResponseRedirect(reverse('tapp:get_clients', args=(user.user_id,)))

tproject/tapp/templates/tapp/about_yandex_direct.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="container">
<ul id="todo-list">
        {% for user in yandex %}
    <li>
        Пользователь: {{ user.user_first_name }} {{ user.user_last_name }}
      <hr/>
    </li>
    <li>
        Email: {{ user.user_email }}
      <hr/>
    </li>
    <li>
        UserID: {{ user.user_id }}
      <hr/>
    </li>
    <li>
        Token: {{ user.token }}
      <hr/>
    </li>
        {% endfor %}
</ul>
</div>
</body>
</html>

tproject/tapp/templates/tapp/client_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список подключений</title>
        {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
    <div class="container">
    <h1>Список подключений для: {{ client }}</h1>
    {% if yandex_direct %}
    <p class="client">
        <a href="{% url 'tapp:about_yandex_direct' user_id client_id %}">Есть активное подключение</a>
        <a href="{% url 'tapp:yandex_code' %}"><button class="add">Обновить подключение</button></a>
    </p>
    {% else %}
    <p class="client">
        Нет активных подключений
        <a href="{% url 'tapp:yandex_code' %}"><button class="add">Создать подключение</button></a>
    </p>
    {% endif %}
    </div>
</body>
</html>

tproject/tapp/templates/tapp/clients.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Список клиентов</title>
        {% load static %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>
<body>
<div class="container">
    <h1>Список клиентов:</h1>
    <ul id="todo-list">
        {% for client in all_clients %}
    <li>
      <a href="{% url 'tapp:get_clients_info' client.user_id client.client_id %}">{{ client.client_name }}</a>
      <a class="remove" href="{% url 'tapp:delete_client' client.user_id client.client_id %}">X</a>
      <hr/>
    </li>
        {% endfor %}
    </ul>
    <form action="." method="post">
        <input type="text" name="client_name">
        {% csrf_token %}
        <button class="add" type="submit">Добавить клиента</button>
    </form>
</div>
</body>
</html>